### ISSUE TITLE
Restore older version source

### ISSUE THREAD

**Issue by kadwanev** [RavenPack/python-api#1]
In case you don't realize it, your 1.x releases are unusable because of:
```
/ravenpackapi/__init__.py in <module>()
----> 1 from .models.dataset import Dataset
      2 from .core import RPApi

ImportError: No module named models.dataset
```
You have apparently force pushed this version and so it's not viewable on github. You chose not to use branches or tags to do what you wanted.

**Comment by dariosky** [comment]
Hi Neville,
the old 1.0 beta API is still available [here](https://github.com/RavenPack/python-api-0.1-beta).
It is deprecated and is going to be dismissed soon, so you may want to use the new 1.0 API (that will be also stable and backward compatible). As part of this release you'll get also various benefits, as the addition of new endpoints and support for indicator datasets.
The new Python API also has more pythonic style, I'm sure you'll love it.

**Comment by kadwanev** [comment]
Thanks. Any comment on the error I'm having with the 1.0 client?

**Comment by dariosky** [comment]
The `models` package should be present, and as well the dataset.py inside.
Did you maybe cloned the new package over the new api?
In that case, starting fresh would help you.
