### ISSUE TITLE
Dependency on dead project `retry` 

### ISSUE THREAD

**Issue by apmorton** [RavenPack/python-api#18]
`retry` is not being maintained, and exports a false dependency on `py`, which is _also_ not being maintained.

This is causing some pretty [convoluted issues](https://youtrack.jetbrains.com/issue/PY-73439/Pycharm-doesnt-stop-at-breakpoints-when-importing-shiboken6-and-py) in our environment.

The core logic for `retry` is pretty simple and could be inlined into this project to resolve this - or swapped for another similar library that is being maintained: https://pypi.org/project/tenacity/

See:
- https://github.com/invl/retry/issues
- https://github.com/pytest-dev/py

**Comment by joserc87** [comment]
@apmorton The latest version [v1.1.5](https://pypi.org/project/ravenpackapi/1.1.5/) doesn't depend on `retry` nor `py` but on `tenacity`. I hope that solves the issues you were having in your environment :four_leaf_clover:
