### ISSUE TITLE
"Not authorized"

### ISSUE THREAD

**Issue by xndxcsd** [RavenPack/python-api#2]
I got the response "Not authorized" when I run the example "get_realtime_news.py". I can access the other api endpoint with my api key . I have a valid key.
What happened ? Why can't I use the get_realtime_news endpoint ？
Thx.

> ravenpackapi.exceptions.APIException: Got an error 403: body was '<head><title>Not authorized</title></head>'

**Comment by dariosky** [comment]
Hi Chen,
I suggest contacting RavenPack client support at support@ravenpack.com or via Intercom.
They'll be able to assist you, checking your credentials and permissions.

**Comment by xndxcsd** [comment]
OK. Thank you for your reply.
