### ISSUE TITLE
Http call issues 

### ISSUE THREAD

**Issue by psriramula** [RavenPack/python-api#4]
Hi There,

I am using your API to connect to a local Mock Raven server

and facing following error.

requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /XXXXXXXXXXXX (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fecd1003518>: Failed to establish a new connection: [Errno 111] Connection refused',))

part of the error stack trace 

 File "/usr/local/lib/python3.6/site-packages/ravenpackapi/models/dataset.py", line 232, in request_realtime
ravenpack        |     stream=True,

**Comment by psriramula** [comment]
Any chance to know what are the headers set to this call. 

https://github.com/RavenPack/python-api/blob/master/ravenpackapi/models/dataset.py#L230-L233

**Comment by dariosky** [comment]
Good day Prasad,
I suppose your mocked RavenPack server listening on port 3000 is an http server that support streaming. That is what the real RavenPack server does.
In your case the error is quite self-explanatory: you're not able to connect to your localhost endpoint.
What is your use-case by the way?

**Comment by psriramula** [comment]
Hi @dariosky  thanks for the quick response,

I am trying to build a integration/performance test stack for one of the product.

where I want to control the test data come from the RavenPack, in absense of a Mock server I tried to build a light weight web server and overided value for the local server some thing like below.

rp_api._FEED_BASE_URL = "http://localhost:3000"

As you mentioned , http connection handshake seems failing.

**Comment by psriramula** [comment]
Seems like I have to make my server to support streaming, alternatively do you guys have any Mock server instance for your customers ?!.

Thanks alot @dariosky

**Comment by dariosky** [comment]
Hi Prasad, at the moment we don't have a simple mocked server example that we can share, but surely we can help.
Flask, for example, supports text streaming returning generators or we can build something more sophisticated with aiohttp - is this something that you need to prove latency of your processing or is it just to test correctness give some known input?

**Comment by psriramula** [comment]
Good morning @dariosky ,

Need to prove latency of my service, Thanks for the advise. I shall try Flask or aiohttp.

**Comment by dariosky** [comment]
Perfect, feel free to contact us via support if anything else is needed.
I'll close this issue.

**Comment by psriramula** [comment]
Hi @dariosky 

I worked on this task, this afternoon and faced some issues with headers.

and managed to create some mock server, looking for some further assitance. Shall add to this issue or open a new issue.

**Comment by psriramula** [comment]
I created my Mock Server as follows 

`from flask import Flask
from flask import stream_with_context, Response
app = Flask(__name__)


@app.route('/stream/<data_set_id>')
def streamed_response(data_set_id):
    def generate(data_set_id):
        path = data_set_id + '.txt'
        file = open(path)
        line = file.readline()
        while line:
            yield line
            line = file.readline()
        file.close()

    headers = {

    }
    return Response(stream_with_context(generate(data_set_id)), headers=headers)


if __name__ == '__main__':
    app.run()`


and with some test data file with in the same directory as : 
`OrderedDict([('TIMESTAMP_UTC', datetime.datetime(2019, 3, 22, 16, 2, 5, 915000)), ('RP_STORY_ID', '4A8529B33F3AF11BE14073502485FF36'), ('RP_ENTITY_ID', '3F1BBA'), ('ENTITY_TYPE', 'ORGA'), ('ENTITY_NAME', 'Government of Algeria'), ('COUNTRY_CODE', 'DZ'), ('RELEVANCE', 36), ('EVENT_SENTIMENT_SCORE', None), ('EVENT_RELEVANCE', None), ('EVENT_SIMILARITY_KEY', None), ('EVENT_SIMILARITY_DAYS', None), ('TOPIC', None), ('GROUP', None), ('TYPE', None), ('SUB_TYPE', None), ('PROPERTY', None), ('FACT_LEVEL', None), ('RP_POSITION_ID', None), ('POSITION_NAME', None), ('EVALUATION_METHOD', None), ('MATURITY', None), ('EARNINGS_TYPE', None), ('EVENT_START_DATE_UTC', None), ('EVENT_END_DATE_UTC', None), ('REPORTING_PERIOD', None), ('REPORTING_START_DATE_UTC', None), ('REPORTING_END_DATE_UTC', None), ('RELATED_ENTITY', None), ('RELATIONSHIP', None), ('CATEGORY', None), ('EVENT_TEXT', None), ('NEWS_TYPE', 'FULL-ARTICLE'), ('RP_SOURCE_ID', '5026D2'), ('SOURCE_NAME', 'Digital Journal'), ('CSS', 0.04), ('NIP', -0.3), ('PEQ', 0), ('BEE', 0), ('BMQ', 1), ('BAM', 0), ('BCA', 0), ('BER', 0), ('ANL_CHG', 0), ('MCQ', 0), ('RP_STORY_EVENT_INDEX', 4), ('RP_STORY_EVENT_COUNT', 7), ('PRODUCT_KEY', 'RPA'), ('PROVIDER_ID', 'MRVR'), ('PROVIDER_STORY_ID', '10:38819205105'), ('HEADLINE', 'Algeria stages new mass protests against Bouteflika')])
OrderedDict([('TIMESTAMP_UTC', datetime.datetime(2019, 3, 22, 16, 2, 5, 915000)), ('RP_STORY_ID', '4A8529B33F3AF11BE14073502485FF36'), ('RP_ENTITY_ID', '3F1BBA'), ('ENTITY_TYPE', 'ORGA'), ('ENTITY_NAME', 'Government of Algeria'), ('COUNTRY_CODE', 'DZ'), ('RELEVANCE', 36), ('EVENT_SENTIMENT_SCORE', None), ('EVENT_RELEVANCE', None), ('EVENT_SIMILARITY_KEY', None), ('EVENT_SIMILARITY_DAYS', None), ('TOPIC', None), ('GROUP', None), ('TYPE', None), ('SUB_TYPE', None), ('PROPERTY', None), ('FACT_LEVEL', None), ('RP_POSITION_ID', None), ('POSITION_NAME', None), ('EVALUATION_METHOD', None), ('MATURITY', None), ('EARNINGS_TYPE', None), ('EVENT_START_DATE_UTC', None), ('EVENT_END_DATE_UTC', None), ('REPORTING_PERIOD', None), ('REPORTING_START_DATE_UTC', None), ('REPORTING_END_DATE_UTC', None), ('RELATED_ENTITY', None), ('RELATIONSHIP', None), ('CATEGORY', None), ('EVENT_TEXT', None), ('NEWS_TYPE', 'FULL-ARTICLE'), ('RP_SOURCE_ID', '5026D2'), ('SOURCE_NAME', 'Digital Journal'), ('CSS', 0.04), ('NIP', -0.3), ('PEQ', 0), ('BEE', 0), ('BMQ', 1), ('BAM', 0), ('BCA', 0), ('BER', 0), ('ANL_CHG', 0), ('MCQ', 0), ('RP_STORY_EVENT_INDEX', 4), ('RP_STORY_EVENT_COUNT', 7), ('PRODUCT_KEY', 'RPA'), ('PROVIDER_ID', 'MRVR'), ('PROVIDER_STORY_ID', '10:38819205105'), ('HEADLINE', 'Algeria stages new mass protests against Bouteflika')])
OrderedDict([('TIMESTAMP_UTC', datetime.datetime(2019, 3, 22, 16, 2, 6, 185000)), ('RP_STORY_ID', '429EE35B2E83DCAE5EBA97D68ADD6B8B'), ('RP_ENTITY_ID', '683532'), ('ENTITY_TYPE', 'ORGA'), ('ENTITY_NAME', 'Organisation of Islamic Cooperation'), ('COUNTRY_CODE', 'XX'), ('RELEVANCE', 42), ('EVENT_SENTIMENT_SCORE', None), ('EVENT_RELEVANCE', None), ('EVENT_SIMILARITY_KEY', None), ('EVENT_SIMILARITY_DAYS', None), ('TOPIC', None), ('GROUP', None), ('TYPE', None), ('SUB_TYPE', None), ('PROPERTY', None), ('FACT_LEVEL', None), ('RP_POSITION_ID', None), ('POSITION_NAME', None), ('EVALUATION_METHOD', None), ('MATURITY', None), ('EARNINGS_TYPE', None), ('EVENT_START_DATE_UTC', None), ('EVENT_END_DATE_UTC', None), ('REPORTING_PERIOD', None), ('REPORTING_START_DATE_UTC', None), ('REPORTING_END_DATE_UTC', None), ('RELATED_ENTITY', None), ('RELATIONSHIP', None), ('CATEGORY', None), ('EVENT_TEXT', None), ('NEWS_TYPE', 'FULL-ARTICLE'), ('RP_SOURCE_ID', '1188B0'), ('SOURCE_NAME', 'Anadolu Ajansi'), ('CSS', 0.0), ('NIP', -0.34), ('PEQ', 0), ('BEE', 0), ('BMQ', 0), ('BAM', 0), ('BCA', 0), ('BER', 0), ('ANL_CHG', 0), ('MCQ', 0), ('RP_STORY_EVENT_INDEX', 3), ('RP_STORY_EVENT_COUNT', 9), ('PRODUCT_KEY', 'RPA'), ('PROVIDER_ID', 'MRVR'), ('PROVIDER_STORY_ID', '10:38819204999'), ('HEADLINE', 'Turkish singer holds concert for New Zealand victims')])`

At this stage I know 

1. Add appropriate headers to the mock server ( lines betwen 18 to 19 )
2. Adjust the data or parse in a format the client can consume

Please see the light weight client application 

`from ravenpackapi import RPApi

api = RPApi(api_key="XXXXXXXXXXXXXXX")
api._FEED_BASE_URL = 'http://localhost:5000/stream'

ds = api.get_dataset(dataset_id='8B251EE392BBBEEE8E5DB852C7101D04')
for msg in ds.request_realtime():
    print(msg)`

**Comment by psriramula** [comment]
Please suggest if I am missing any authentication part in the mock server

**Comment by psriramula** [comment]
Appreciate your assitance in this regard.

**Comment by dariosky** [comment]
Hi Prasad,
I think it's better to move this in a better media, this is not really related to the API itself.
You can contact us via support@ravenpack.com and I'll be sure to follow your issue.
Thanks
