### ISSUE TITLE
Does it supports proxy setting?

### ISSUE THREAD

**Issue by pengxianggui** [RavenPack/python-api#5]
We can't visit ravenpack.com, but we can visit through proxy server. So does it support proxy setting?

**Comment by dariosky** [comment]
Good morning Mike,
Sure. We are using the requests library to do https requests.
You can set the HTTPS_PROXY environment variable to set your proxy.
The documentation about the proxy in requests [can be found here](https://2.python-requests.org//en/master/user/advanced/#proxies).

In the latest version (1.0.26) you can also provide custom parameters to all your requests (like the proxies one), so you are able to do something like:
```
api = RPApi()
api.common_request_params['proxies'] = {
  'https': 'http://your_internal_proxy:9999',
}
```
And then use the library normally

**Comment by pengxianggui** [comment]
> Good morning Mike,
> Sure. We are using the requests library to do https requests.
> You can set the HTTPS_PROXY environment variable to set your proxy.
> The documentation about the proxy in requests [can be found here](https://2.python-requests.org//en/master/user/advanced/#proxies).
> 
> In the latest version (1.0.26) you can also provide custom parameters to all your requests (like the proxies one), so you are able to do something like:
> 
> ```
> api = RPApi()
> api.common_request_params['proxies'] = {
>   'https': 'http://your_internal_proxy:9999',
> }
> ```
> And then use the library normally

Hi, dariosky, thank you. It works!
But there is another error occur: requests.exceptions.SSLError. I want to add config like : verify=false. But i don't know how to config with ravenpackapi:1.0.26.   Is there any API reference?

**Comment by dariosky** [comment]
That was exactly the use-case for introducing the common_request_params in the first place :+1: 
It wasn't a common request, but surely we'll add it to the documentation soon.

For your example, here's the updated code to add both params to all the requests:

```
api = RPApi()
api.common_request_params['proxies'] = {
  "verify": False,
  'https': 'http://your_internal_proxy:9999',
}
```

**Comment by pengxianggui** [comment]
> That was exactly the use-case for introducing the common_request_params in the first place 👍
> It wasn't a common request, but surely we'll add it to the documentation soon.
> 
> For your example, here's the updated code to add both params to all the requests:
> 
> ```
> api = RPApi()
> api.common_request_params['proxies'] = {
>   "verify": False,
>   'https': 'http://your_internal_proxy:9999',
> }
> ```

It looks like no effect. May be the problem is with me, I'll try to solve is. Thank you, dariosky.

**Comment by pengxianggui** [comment]
> > That was exactly the use-case for introducing the common_request_params in the first place 👍
> > It wasn't a common request, but surely we'll add it to the documentation soon.
> > For your example, here's the updated code to add both params to all the requests:
> > ```
> > api = RPApi()
> > api.common_request_params['proxies'] = {
> >   "verify": False,
> >   'https': 'http://your_internal_proxy:9999',
> > }
> > ```
> 
> It looks like no effect. May be the problem is with me, I'll try to solve is. Thank you, dariosky.

Hi, dariosky. I think I solved it. The right way as follow:

```
api.common_request_params['proxies'] = {
  'https': 'http://your_internal_proxy:9999'
}
api.common_request_params['verify'] = False

I hope it's helpful to others.

**Comment by dariosky** [comment]
I'm glad you found it Mike!
Absolutely, "verify" was not supposed to stay in "proxies".

For the reference, for setting multiple parameters, the idea was to do something like this:
```
api.common_request_params.update(
        dict(proxies={'https': 'http://your_internal_proxy:9999'},
             verify=False
             )
    )
```
Don't hesitate to contact us for any further doubt. Resolving.
