### ISSUE TITLE
Dataset control

### ISSUE THREAD

**Issue by TSmithSmith** [RavenPack/python-api#6]
Hi there, is there a way to edit the filters on an existing dataset, or delete datasets through the API?
Currently I am having to make a new dataset every time I want to change the filters. 
I see in the api documentation this functionality does exist but can't find where the functions for this are in the python wrapper.
Thanks!

**Comment by dariosky** [comment]
Hi @TSmithSmith - thanks for writing us (I would suggest writing to support@ravenpack.com in the future).

You can see editing a dataset to make different requests in our [indicator_dataset example](https://github.com/RavenPack/python-api/blob/master/ravenpackapi/examples/indicator_datasets.py) - it's really simple:
to change the filters of a given dataset you just change `dataset.filters` to a new dictionary and call `dataset.save()`.
It would raise a ValidationError in case something is wrong with your filters.

To delete a dataset is also easy: just call `dataset.delete()`.

Hope this will help.

**Comment by TSmithSmith** [comment]
Ah fantastic! Thank you! 
Tom
