### ISSUE TITLE
Get connectionResetError when a session is reused

### ISSUE THREAD

**Issue by lukesavva** [RavenPack/python-api#7]
When a request is made using a new session it is successful but as soon as that session is reused i get a ConnectionResetError.
A temporary work around i have used is to replace the session on the RPApi object with requests.
    def test_create(rp_data_source: RavenpackDataSource):
>       df = rp_data_source.get_time_series('Production Delays')

tests\data\test_ravenpack_data_source.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
src\lib\data\abstract_data_source.py:59: in wrapper
    data = func(series, start_date, end_date, *args, **kwargs)
src\lib\data\ravenpack_data_source.py:28: in get_time_series
    [self.query_single(x, start_date, end_date) for x in datasets]
src\lib\data\ravenpack_data_source.py:28: in <listcomp>
    [self.query_single(x, start_date, end_date) for x in datasets]
src\lib\data\ravenpack_data_source.py:34: in query_single
    job.wait_for_completion()
C:\Users\Luke.Savva\AppData\Local\pypoetry\Cache\virtualenvs\researchpythonlibrary-FcWUxGnF-py3.9\lib\site-packages\ravenpackapi\exceptions.py:60: in decorated_func
    return func(instance, *args, **kwargs)
C:\Users\Luke.Savva\AppData\Local\pypoetry\Cache\virtualenvs\researchpythonlibrary-FcWUxGnF-py3.9\lib\site-packages\ravenpackapi\models\job.py:92: in wait_for_completion
    self.get_status()
C:\Users\Luke.Savva\AppData\Local\pypoetry\Cache\virtualenvs\researchpythonlibrary-FcWUxGnF-py3.9\lib\site-packages\ravenpackapi\exceptions.py:60: in decorated_func
    return func(instance, *args, **kwargs)
C:\Users\Luke.Savva\AppData\Local\pypoetry\Cache\virtualenvs\researchpythonlibrary-FcWUxGnF-py3.9\lib\site-packages\ravenpackapi\models\job.py:53: in get_status
    response = self.api.request(
C:\Users\Luke.Savva\AppData\Local\pypoetry\Cache\virtualenvs\researchpythonlibrary-FcWUxGnF-py3.9\lib\site-packages\ravenpackapi\core.py:96: in request
    response = requests_call(
C:\Users\Luke.Savva\AppData\Local\pypoetry\Cache\virtualenvs\researchpythonlibrary-FcWUxGnF-py3.9\lib\site-packages\ravenpackapi\utils\dynamic_sessions.py:35: in get_session_method
    return getattr(session, method)(*args, **kwargs)
C:\Users\Luke.Savva\AppData\Local\pypoetry\Cache\virtualenvs\researchpythonlibrary-FcWUxGnF-py3.9\lib\site-packages\requests\sessions.py:555: in get
    return self.request('GET', url, **kwargs)
C:\Users\Luke.Savva\AppData\Local\pypoetry\Cache\virtualenvs\researchpythonlibrary-FcWUxGnF-py3.9\lib\site-packages\requests\sessions.py:542: in request
    resp = self.send(prep, **send_kwargs)
C:\Users\Luke.Savva\AppData\Local\pypoetry\Cache\virtualenvs\researchpythonlibrary-FcWUxGnF-py3.9\lib\site-packages\requests\sessions.py:655: in send
    r = adapter.send(request, **kwargs)

**Comment by dariosky** [comment]
Hi @lukesavva - sorry for the very late answer. When I read your message I was needing some more information about how you are "reusing the session", and maybe the exception you're getting.
If this is still a problem - feel free to reopen this issue.
