### ISSUE TITLE
Is it possible to filter documents by source?

### ISSUE THREAD

**Issue by igygi** [RavenPack/python-api#8]
Hi, 

I have a few questions about querying with a source filter:

- Is it possible to filter the query such that it returns just the articles from a given list of sources?
- Is it possible to get a list of the supported sources in Ravenpack?

**Comment by dariosky** [comment]
Good day,
Sorry for the delay, I would suggest using support@ravenpack.com or the chat on our website to get support and suggestions, both about our data and about how to use it via Python.
To quickly answer your questions ("yes" in both cases):

You can filter by `rp_source_id` or by `provider_id` - here in RPA - for example this is the Dataset payload
```
{
  "product": "rpa",
  "product_version": "1.0",
  "fields": null,
  "name": "Filtering by source",
  "filters": {
    "$or": [
      {
        "rp_source_id": {
          "$in": [
            "B5569E"
          ]
        }
      },
      {
        "provider_id": {
          "$in": [
            "BZG"
          ]
        }
      }
    ]
  },
  "frequency": "granular"
}
```

You can get all the available sources using our entity reference file - with type SRCE - here an example.
https://github.com/RavenPack/python-api/blob/master/ravenpackapi/examples/query_entity_types_reference.py

**Comment by igygi** [comment]
Great, thanks @dariosky!
